# Generated by Django 5.2.7 on 2025-11-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artistas', models.CharField(max_length=300)),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('total_canciones', models.IntegerField()),
                ('imagen', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('followers', models.IntegerField()),
                ('imagen', models.URLField(blank=True)),
                ('popularidad', models.IntegerField()),
                ('nacionalidad', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('artistas', models.CharField(max_length=300)),
                ('estilo', models.CharField(max_length=100)),
                ('reproducciones', models.IntegerField()),
                ('duracion', models.IntegerField(help_text='Duración en segundos')),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('album', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
