# Generated by Django 5.2.7 on 2025-11-05 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptop100', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artistas',
        ),
        migrations.AlterField(
            model_name='cancion',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canciones', to='apptop100.album'),
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='artistas',
        ),
        migrations.AlterField(
            model_name='cancion',
            name='estilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='apptop100.estilo'),
        ),
        migrations.AddField(
            model_name='album',
            name='artistas',
            field=models.ManyToManyField(related_name='albumes', to='apptop100.artista'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='artistas',
            field=models.ManyToManyField(related_name='canciones', to='apptop100.artista'),
        ),
    ]
